'use client';

export const homeListings = [
    {
      name: 'SOJI SADIKU VENTURES',
      image: '/images/soji.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Providing top-quality services with exceptional customer satisfaction. Experience excellence with SOJI SADIKU VENTURES.',
      price: '500K - upward',
      reviews: '60',
      rating: 3.2,
    },
    {
      name: 'DAVID PHOTOGRAPHY',
      image: '/images/david.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Capture your precious moments with professional photography services. Trust us for stunning and memorable shots.',
      price: '800K - upward',
      reviews: '60',
      rating: 4,
    },
    {
      name: 'KEMI CATERING SERVICES',
      image: '/images/kemi.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Indulge in delicious and delectable dishes prepared by us. Experience culinary delights that will leave you craving for more.',
      price: '600K - upward',
      reviews: '60',
      rating: 3.8,
    },
    {
      name: 'JOHN CINEMATOGRAPHY',
      image: '/images/john.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Capture your special moments with the magic of cinema. Trust JOHN CINEMATOGRAPHY to create captivating videos that will tell your story.',
      price: '1M - upward',
      reviews: '60',
      rating: 2.4,
    },
    {
      name: 'ABEL’S DJ CENTER',
      image: '/images/abel.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Get the party started with the energetic beats and seamless mixes from ABEL’S DJ CENTER. Dance the night away with the best tunes in town.',
      price: '700K - upward',
      reviews: '60',
      rating: 4,
    },
    {
      name: 'ANABEL MAKEUP CLASSIC',
      image: '/images/annabel.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Enhance your beauty and radiate confidence with the expert touch of ANABEL MAKEUP CLASSIC. Look stunning for any occasion.',
      price: '400K - upward',
      reviews: '60',
      rating: 3.6,
    },
    {
      name: 'GOOD WEARS TAILORING',
      image: '/images/goodwear.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Step into fashion excellence with GOOD WEARS TAILORING. Experience personalized tailoring that will make you stand out from the crowd.',
      price: '900K - upward',
      reviews: '60',
      rating: 2.3,
    },
    {
      name: 'MC WHYK',
      image: '/images/mc.png',
      address: '43, Marian close, Magodo, Lagos.',
      description: 'Turn your event into an unforgettable experience with the hosting skills of MC WHYK. Engage your audience and create memorable moments.',
      price: '1.2M - upward',
      reviews: '60',
      rating: 3.9,
    },
];
  
