export const vendorsListings = [
    {
        name: 'SOJI SADIKU CAKES',
        image: '/images/sojiCakes.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Indulge in a delectable variety of cakes and pastries crafted with love and expertise by Soji Sadiku Cakes.',
        price: '500K - upward',
        reviews: '60',
        rating: 4.3,
    },
    {
        name: 'JANE BAKING CENTER',
        image: '/images/cooperBakes.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into the world of heavenly baked goods at Jane Baking Center. Our passion for baking is evident in every bite of our delicious creations.',
        price: '200K - upward',
        reviews: '50',
        rating: 4,
    },
    {
        name: 'ESTHER CRUNCHIES',
        image: '/images/estherCrunches.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Treat yourself to the irresistible goodness of our Crunchies. Our snacks are a perfect blend of flavors that will leave you wanting more.',
        price: '100K - upward',
        reviews: '70',
        rating: 3,
    },
    {
        name: 'BUKKS CONFECTIONERIES',
        image: '/images/confectionaries.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Indulge in the world of confectionery delights. From mouth-watering cakes to exquisite pastries, we offer a wide range of sweet treats.',
        price: '100K - upward',
        reviews: '10',
        rating: 3.8,
    },
    {
        name: 'TOBA PHOTOS',
        image: '/images/john.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Capture the moments that matter with Toba Photos. Our skilled photographers are dedicated to preserving your precious memories in the most captivating way.',
        price: '500K - upward',
        reviews: '120',
        rating: 2.8,
    },
    {
        name: 'TOLU UNITS',
        image: '/images/units.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into the world of fashion excellence with Tolu Units. Our skilled tailors and designers are passionate about creating personalized outfits that make you stand out from the crowd.',
        price: '200K - upward',
        reviews: '120',
        rating: 4,
    },
    {
        name: 'BIG DADDY PICTURES',
        image: '/images/bigdaddyPhotos.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Preserve your precious moments with Big Daddy Pictures. Our team of experienced photographers is dedicated to capturing the essence of every occasion.',
        price: '100K - upward',
        reviews: '30',
        rating: 3,
    },
    {
        name: 'ANDY BEST PHOTOS',
        image: '/images/andyPhotos.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Our team of talented photographers combines creativity and technical expertise to deliver breathtaking photographs that will preserve your memories for a lifetime.',
        price: '100K - upward',
        reviews: '50',
        rating: 3.8,
    },
    {
        name: 'FACE AND BEAUTY',
        image: '/images/beauty.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Enhance your natural beauty with Face and Beauty. Our team of skilled makeup artists and stylists are dedicated to bringing out your best features and creating a flawless look.',
        price: '50K - upward',
        reviews: '50',
        rating: 4,
    },
    {
        name: 'BEAUTY CHANGE ',
        image: '/images/beautyChange.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Experience a transformation with Beauty Change. Our team of skilled professionals specializes in hair and beauty services that will enhance your natural beauty and bring out your unique style.',
        price: '20K - upward',
        reviews: '20',
        rating: 4.5,
    },
    {
        name: 'HANDS TOUCH',
        image: '/images/touch.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Relax and rejuvenate at Hands Touch. Our skilled therapists offer a range of spa and massage services that will melt away your stress and leave you feeling refreshed.',
        price: '10K - upward',
        reviews: '30',
        rating: 4.2,
    },
    {
        name: 'BEAUTY CENTER',
        image: '/images/beautyCenter.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into a world of beauty at Beauty Center. Our skilled team of professionals is dedicated to enhancing your natural beauty and providing personalized beauty services.',
        price: '10K - upward',
        reviews: '60',
        rating: 3
    },
    {
        name: 'TOUCH TAILORING',
        image: '/images/touchTailor.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into the world of fashion excellence with Touch Tailoring. Our experienced tailors provide personalized tailoring services that cater to your unique style.',
        price: '5K - upward',
        reviews: '50',
        rating: 2.5
    },
    {
        name: 'NICE OUTFIT',
        image: '/images/nice.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Discover a world of stylish outfits at Nice Outfit. Our talented team of designers creates fashionable and trendy clothing that reflects your unique personality.',
        price: '70K - upward',
        reviews: '50',
        rating: 3.5
    },
    {
        name: 'OUTFIT AND CRAFT',
        image: '/images/outfit.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into the world of fashion excellence with Outfit and Craft. Our skilled team of designers and artisans create unique and custom-made outfits that showcase your individual style.',
        price: '50K - upward',
        reviews: '35',
        rating: 4
    },
    {
        name: 'BLESSING TAILORING',
        image: '/images/trusted.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Trust your fashion needs to Trusted Blessing Tailoring. With our team of skilled tailors and designers, we provide personalized tailoring services that exceed your expectations.',
        price: '10K - upward',
        reviews: '63',
        rating: 3.8
    },
    {
        name: 'STYLES AND CLASS EVENTS',
        image: '/images/styles.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into a world of elegance with Styles and Class Events. Our experienced event planners and designers create memorable and extraordinary events that leave a lasting impression.',
        price: '50K - upward',
        reviews: '39',
        rating: 4.8
    },
    {
        name: 'ALL ROUND EVENTS',
        image: '/images/all.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'At All Round Events, we specialize in creating unforgettable experiences. Our team of event planners and coordinators meticulously plan and execute a wide range of events.',
        price: '80K - upward',
        reviews: '36',
        rating: 4
    },
    {
        name: 'JAMES AND KEMI CENTER',
        image: '/images/jk.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Discover the epitome of luxury and elegance at James and Kemi Center. Our exclusive event venue offers a sophisticated setting for weddings, parties, and corporate events.',
        price: '200K - upward',
        reviews: '30',
        rating: 4
    },
    {
        name: 'BEAUTY AND LIFE CENTER',
        image: '/images/life.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Indulge in a world of beauty and rejuvenation at Beauty and Life Center. Our skilled therapists and beauty experts offer a range of services, including skincare treatments, massages, and more.',
        price: '150K - upward',
        reviews: '43',
        rating: 4.8
    },
    {
        name: 'CLASSIC HAIRCUT',
        image: '/images/classic.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into Classic Haircut and discover the art of hairstyling. Our experienced barbers provide classic and trendy haircuts that suit your style and personality.',
        price: '50K - upward',
        reviews: '100',
        rating: 4
    },
    {
        name: 'DEEDEE HAIR CENTER',
        image: '/images/deedee.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'With attention to detail and the latest techniques, we create hairstyles that enhance your natural beauty and reflect your individuality. Experience the artistry of hairdressing at Deedee Hair Center.',
        price: '25K - upward',
        reviews: '80',
        rating: 4.3
    },
    {
        name: 'ALL STYLES BEAUTY',
        image: '/images/allStyles.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Step into All Styles Beauty and discover a world of beauty services. Our skilled beauty professionals provide a wide range of treatments, including makeup, skincare, manicures, and pedicures.',
        price: '15K - upward',
        reviews: '110',
        rating: 4.2
    },
    {
        name: 'ONE AND GOOD BEAUTY',
        image: '/images/good.png',
        address: '43, Marian close, Magodo, Lagos.',
        description: 'Indulge in beauty at its best with One and Good Beauty. Our team of skilled beauticians offers a wide range of services, including makeup, hairstyling, skincare, and more.',
        price: '5K - upward',
        reviews: '150',
        rating: 3.8
    }
]