export const vendorsListings = [
    {
        name: 'Pakaard Media',
        image: '/images/Pakaard.png',
        description: 'Pakaard is a media outfit specialized in delivering beautiful top notch images at very affordable rates for all events.',
        job: 'photography video photo videography',
        location: 'Abuja, Nigeria.',
        fullname: 'Iyanuoluwa',
        phone: '08100308391',
        social: 'IG: pakaard',
        service: 'Photographer',
        experience: '2 years',
    },
    {
        name: 'Moncherri Confectionery',
        image: '/images/Moncherri_Confectionery.png',
        description: 'Mon Cherri Confectionery is a brand that gives delicious cakes and pastries that is perfect for any occasion. It is made with high-quality ingredients, and is baked to perfection for a moist, tender texture.',
        job: 'catering chef cake',
        location: 'Muftau Raji Street, Orelope, Lagos.',
        fullname: 'Okeya Ayotomiwa',
        phone: '08036815819',
        social: 'Moncherri_Confectionery',
        service: 'Baker',
        experience: '2 years',
    },
    {
        name: 'Cherry Gold Confectionery',
        image: '/images/Cherry.png',
        description: 'Cherry Gold Confectionery we offer our customer yummy, beautiful, mouth watering birthday cake , small chops and pastries with a touch of love.',
        job: 'catering cake pasteries small chops',
        location: 'Abuja',
        fullname: 'Adewale Sherifat',
        phone: '08105050078',
        social: ' IG @cherry_gold.confectionery',
        service: 'Baker',
        experience: '3 years',
    },
    {
        name: 'Mercuria Business Network',
        image: '/images/mercuria.png',
        description: 'We are into delivering services for event and catering.',
        job: 'event planner business catering',
        location: 'Plot 13 J Line,Ewet Housing Estate, Uyo, Akwa Ibom.',
        fullname: 'Nkese Eyo',
        phone: '07039584426',
        social: '@Mercuriachops@Memo',
        service: 'Event Decorator',
        experience: '12 years',
    },
    {
        name: 'Wildcard prints',
        image: '/images/wildcard.png',
        description: 'Wildcard prints is a company that gives bespoke printing services for all events and gatherings. We are your go to for achieving high quality design and branding for your events, from your invitation cards, to your roll up banners down to souvenirs we got you covered.',
        job: 'printing design branding invitation iv card banner souvenirs',
        location: '144 Akerele street, Surulere Lagos.',
        fullname: 'Anthony',
        phone: '09125265710',
        social: 'Thread: @wildcard_prints, IG: wildcard_prints',
        service: 'Printer',
        experience: '7 years',
    },
    {
        name: "Jenny's Glam",
        image: '/images/jenny.png',
        description: 'Make up.',
        job: 'makeup',
        location: '4 Soretire street Ogba Lagos.',
        fullname: 'Jennifer Alechenu',
        phone: '09021419373',
        social: 'Jennys_glamm',
        service: 'Beautician',
        experience: '8 years',
    },
    {
        name: "Bee's smoothies and juice",
        image: '/images/bee.png',
        description: 'One stop shop for all your healthy yet, delicious fresh smoothies and juices.',
        job: 'smoothie juice fruit',
        location: 'Abuja',
        fullname: 'Brenda Terry',
        phone: '07061013553',
        social: 'Beessmoothiesandjuice',
        service: 'Fresh fruits juice/smoothies',
        experience: '4 years',
    },
    {
        name: 'Chef nahnah Foods',
        image: '/images/nahnah.png',
        description: 'Chef Nahnah foods and confectionary ltd is a modern and exquisite pastry company that produces food and treats cutting across all classes, with a mission to create a one-stop experience that offers affordable food services.',
        job: 'chef food cook',
        location: '17 amodu close, miccom bustop, egbeda, Lagos.',
        fullname: 'Nancy Amaku',
        phone: '+2348188002579',
        social: '@chef.nahnah',
        service: 'Small chops vendor',
        experience: '3 years',
    },
    {
        name: 'Real Leather',
        image: '/images/real.png',
        description: 'Into Manufacturing of shoes.',
        job: 'cobbler shoe shoemaker leather',
        location: 'FUTA AKURE.',
        fullname: 'Dare Samson',
        phone: '+2348163319574',
        social: 'https://m.facebook.com/realleather',
        service: 'Leather works',
        experience: '5 years',
    },
    {
        name: 'Soo Casual',
        image: '/images/soo.png',
        description: 'Designing.',
        job: 'fashion design fashiondesign',
        location: 'Lugbe Abuja.',
        fullname: 'Soo Jasmine',
        phone: '07035384483',
        social: 'Soo__casual',
        service: 'Fashion',
        experience: '4 years',
    },
    {
        name: 'Mariposa Fruits Co',
        image: '/images/mariposa.png',
        description: 'We sell parfaits, smoothies and juices, fruit trees and chocolate fountains, cocktails and mocktails, salads and sandwiches.',
        job: 'juice fruit smoothie parfait chocolate fountains cocktails mocktails salads sandwiches',
        location: '13, Aanuoluwapo Street, Shomolu, Lagos.',
        fullname: 'Detola Adebiyi',
        phone: '08062712107',
        social: '@mariposa_fruits',
        service: 'Fruits Catering',
        experience: '5 years',
    },
    {
        name: 'His Touch Studios',
        image: '/images/touch.png',
        description: 'His Touch Studios is a professional event Photography company with an experience of over a decade. We are known for quality service and prompt delivery.',
        job: 'photographer photo video videographer',
        location: 'Suite 1 Emeritus professor Ogunlesi multipurpose hall, UCH, Ibadan. Oyo state.',
        fullname: 'Tolulope Adedayo Odusina',
        phone: '08109219897',
        social: '@histouchstudios',
        service: 'Photographer',
        experience: '13 years',
    },
    {
        name: "Surshi’s cuisine",
        image: '/images/surshi.png',
        description: 'Food, snacks, beverages, soup bowls.',
        job: 'food cuisine snacks beverages soup bowls',
        location: '131 road house 17, Gwarinpa first avenue, Abuja.',
        fullname: 'Surshima',
        phone: '07039198856',
        social: 'Surshi’s cuisine (Instagram) surshi’s cuisine (Facebook)',
        service: 'Catering',
        experience: '4 years',
    },
    {
        name: 'Imv hub',
        image: '/images/imv.png',
        description: 'Marketing and technology agency.',
        job: 'marketer marketing promote promoter',
        location: '16, olajide bakare street, Idimu lagos.',
        fullname: 'Olumide Adeyanju',
        phone: '+2348123230461',
        social: '@imvhub',
        service: 'Media',
        experience: '3 years',
    },
    {
        name: 'Maybeth Decors & Events',
        image: '/images/maybeth.png',
        description: 'Maybeth Decors & Event is an event Decoration company based in Lagos that caters for both social & corporate Events. We also have the rental arm of the company.',
        job: 'event planner eventplanner decoration',
        location: '3 Yakoyo road ojodu, Lagos',
        fullname: 'Elizabeth Owoseni',
        phone: '08082709988',
        social: 'www.instagram.com/maybetheventsng',
        service: 'Event Decorator',
        experience: '10 years',
    },
    {
        name: 'Veroni_hairs',
        image: '/images/veroni.png',
        description: 'We deal in all kinds of human hair and accessories.',
        job: 'hairstylist hair vendor',
        location: 'Mabushi, Abuja.',
        fullname: 'Jennifer ogwude',
        phone: '09163181254',
        social: 'veroni_hairs',
        service: 'Beauty and hair care',
        experience: '3 years',
    },
]